language: android
jdk: oraclejdk8

android:
  components:
    - tools
  licenses:
    - android-sdk-license-.+

before_install:
  - openssl aes-256-cbc -K $encrypted_2330f03d7182_key -iv $encrypted_2330f03d7182_iv -in archive.tar.gz.enc -out archive.tar.gz -d
  - tar -xzvf archive.tar.gz
  - chmod +x gradlew
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"

before_script:
  - echo yes | ${ANDROID_HOME}tools/bin/sdkmanager "tools"
  - echo yes | ${ANDROID_HOME}tools/bin/sdkmanager "platform-tools"
  - echo yes | ${ANDROID_HOME}tools/bin/sdkmanager "build-tools;28.0.3"
  - echo yes | ${ANDROID_HOME}tools/bin/sdkmanager "platforms;android-25"

script:
  - ./gradlew clean build

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

deploy:
  provider: releases
  api_key:
    secure: keM4yR/2Kl1AbEKxeoG0gZBfbK3A71PI29UJewvNDmB9pYTR1yBcWwreX+99Mvn785f6kDgCev132Ur6066FB5QnSkE2nfoXCvRqQQS1Fa3JNtqYGLmuAv1ZprmFoNSWuVnuYZ8leqxbabrG9/6A/ojMEefC5Gh5FEIwKH0t4qcYOwlCHJRHY2u+Y3el+8n/pHd0hT+ttLMh6wBzA0gOzKefuhpdIg4JlA8RoGSK2lVCgnBa4rHZiaXRQKQ7HZ3DuCR/usDD0rUp4CmdZh6c91i2LBIC7chWRyfLrOSAwcZRm8aH1HZ1nrAyOTa38c/bQPvgpqT8NDCgGwiWe0Ajmnt+qfnthp0lKrEl6zwSiJL84sNYYR+qOwtCvWA4CMFm+srwLNMSGaIsjLsuKNfAhig7XBeKxjMwSPXRQd4nFFz88PNR4Doe8jYgr5GJcAC0xHB4q1tT0zWs3s/Tf0far6IF8EEIS8sW29EgmvHneB9+dHMadUvQ9nymZO7VFr2JGaE8CtipoyiN1zR/mU6vLQVIQKiM2UD1lnYXeZz0N8G/Vk7FubB/43cN89gL3VuJrFjP+/qedgafISq7Rd0mL4JW2nOix4vhp22+CWHGix/5zWkNui1lm72KX9mPz7bCPU5O/BMa2Tf9HO9vUH87UnkaUMAN88Gw95uLFIgaSMY=
  file: app/build/outputs/apk/app-release.apk
  skip_cleanup: true
  on:
    repo: pautiina/android-ubilling
    tags: true

notifications:
  email: false
